name: Publishing the version
run-name: Publish

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN_PACKAGES }}
  USERNAME: Vijay Gangatharan
  EMAIL: 42581616+Vijay431@users.noreply.github.com

permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - "dev"
      - "stage"
      - "test"
      - "master"
      - "support"
      - "hotfix"

jobs:
  version:
    name: Version
    continue-on-error: false
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"
      - name: Determine Version with git history
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
      - run: npm install
      - name: Publishing package
        run: |
          readonly VERSION=${{ steps.gitversion.outputs.semVer }}
          # git config user.name ${{ env.USERNAME }}
          # git config user.email ${{ env.EMAIL }}

          npm version $VERSION
          # git push
          npm publish
