name: Publishing the version
run-name: Publish

on: push

jobs:
  pull-request:
    if: github.ref == 'refs/heads/dev'
    continue-on-error: true
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: "dev"
          destination_branch: "master"
          pr_title: "[Automation] publishing changes to `master` branch"
          pr_assignee: "Vijay431"
          pr_label: "patch"
          pr_draft: false
          pr_allow_empty: false
          github_token: ${{ secrets.PR_TOKEN }}

  version:
    if: github.ref == 'refs/heads/master'
    name: Version
    runs-on: ubuntu-22.04
    continue-on-error: false
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get Merged Pull Request Info
        id: pr-details
        uses: pablogamboa/action-get-merged-pull-request@v1.1
        with:
          github_token: ${{ secrets.TOKEN_PACKAGES }}
      - name: Read label from merged PR
        run: |
          echo "Reading label from previously closed PR"

          labels=$(echo "${{ steps.pr-details.outputs.labels }}" | tr ',' '\n')
          for label in $labels
          do
            echo "Label: $label"
            if [ $label = 'patch' ]; then
              npm version patch
            elif [ $label = 'minor' ]; then
              npm version minor
            elif [ $label = 'major' ]; then
              npm version major
            fi
          done
      - name: Update the code base into `master`
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Version update
          add_options: --all

  publish:
    if: github.ref == 'refs/heads/master'
    name: Publish
    runs-on: ubuntu-22.04
    needs: version
    continue-on-error: false
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: publishing package...
        run: npm publish
