name: Publishing the version
run-name: Publish

on:
  push:
    branches:
      - "dev"
      - "stage"
      - "test"
      - "master"
      - "support"
      - "hotfix"

jobs:
  version:
    runs-on: ubuntu-22.04
    continue-on-error: false
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Package Versioning...
        run: |
