name: Package Publish
run-name: publish

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN_PACKAGES }}

permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - "master"
      - "support"
      - "hotfix"

jobs:
  version:
    continue-on-error: false
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"
      - name: Determine Version with git history
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
      - name: Publishing package
        run: |
          readonly VERSION=${{ steps.gitversion.outputs.semVer }}
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"

          npm version $VERSION
          npm publish
