name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*.*"

jobs:
  release:
    name: Release
    timeout-minutes: 2
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: false
          generate_release_notes: true
          files: |
            LICENSE
