name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*.*"

jobs:
  release-notes:
    name: Release Notes
    timeout-minutes: 2
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:2.0.1

  release:
    name: Release
    timeout-minutes: 2
    continue-on-error: false
    runs-on: ubuntu-latest
    needs: release-notes
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: false
          files: |
            LICENSE
            release_file.md
